//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ShipEditor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SHIPEDITOR_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_MODIFYBEAM_DIALOG           131
#define IDD_MODIFYTUBE_DIALOG           132
#define IDD_NEWCLASS_DIALOG             134
#define IDD_SHOWSTATS_DIALOG            135
#define IDC_SHIPCLASS                   1000
#define IDC_SHIPDESCRIPTION             1009
#define IDC_SHIPTYPE                    1010
#define IDC_SAVE                        1011
#define IDC_LOAD                        1012
#define IDC_LIST1                       1013
#define IDC_BIOTECH                     1014
#define IDC_ENERGYTECH                  1015
#define IDC_COMPUTERTECH                1016
#define IDC_PROPULSIONTECH              1017
#define IDC_CONSTRUCTIONTECH            1018
#define IDC_WEAPONTECH                  1019
#define IDC_INDUSTRY                    1020
#define IDC_TITAN                       1021
#define IDC_DEUTERIUM                   1022
#define IDC_DURANIUM                    1023
#define IDC_CRYSTAL                     1024
#define IDC_IRIDIUM                     1025
#define IDC_DILITHIUM                   1026
#define IDC_MATERIAL                    1027
#define IDC_RADIO2                      1028
#define IDC_RADIO3                      1029
#define IDC_DOUBLEHULL                  1031
#define IDC_BASEHULL                    1032
#define IDC_MAXSHIELDS                  1033
#define IDC_SHIELDTYPE                  1034
#define IDC_RANGE                       1036
#define IDC_RADIO5                      1037
#define IDC_RADIO6                      1038
#define IDC_SPEED                       1039
#define IDC_SCANPOWER                   1040
#define IDC_SCANRANGE                   1041
#define IDC_STORAGEROOM                 1042
#define IDC_CAMOUFLAGEPOWER             1043
#define IDC_COLONIZATIONPOINTS          1044
#define IDC_STATIONBUILDPOINTS          1045
#define IDC_MAINTENANCECOSTS            1047
#define IDC_BEAMLIST                    1048
#define IDC_MODIFYBEAM                  1049
#define IDC_BEAMNAME                    1050
#define IDC_BEAMTYPE                    1051
#define IDC_BEAMNUMBER                  1052
#define IDC_BEAMDAMAGE                  1053
#define IDC_ADDBEAM                     1054
#define IDC_DELETEBEAM                  1055
#define IDC_TORPEDOLIST                 1056
#define IDC_MODIFYTUBE                  1057
#define IDC_DELETETUBE                  1058
#define IDC_ADDTUBE                     1059
#define IDC_TUBETYPE                    1060
#define IDC_TUBEFIRERATE                1061
#define IDC_TORPEDOTYPE                 1062
#define IDC_NUMBEROFTORPEDOS            1063
#define IDC_NUMBEROFTUBES               1064
#define IDC_NEWCLASS                    1065
#define IDC_NEWCLASSNAME                1066
#define IDC_DELETECLASS                 1067
#define IDC_SHOWSTATS                   1068
#define IDC_OVERALLBEAMDAMAGE           1069
#define IDC_AVERAGETORPEDODAMAGE        1070
#define IDC_MAXSHIELD                   1071
#define IDC_MAXHULL                     1072
#define IDC_FEDERATION                  1088
#define IDC_RADIO14                     1089
#define IDC_RADIO15                     1090
#define IDC_RADIO16                     1091
#define IDC_RADIO17                     1092
#define IDC_RADIO18                     1093
#define IDC_RADIO19                     1094
#define IDC_ONLYMICRO                   1095
#define IDC_ONLYONSYSTEM                1097
#define IDC_MANEUVER                    1098
#define IDC_SHIPSIZE                    1099
#define IDC_MODULATING                  1101
#define IDC_ABLATIVE                    1102
#define IDC_REGENERATIVE                1103
#define IDC_SPECIAL1                    1104
#define IDC_SPECIAL2                    1105
#define IDC_OBSOLETE                    1106
#define IDC_ACCURACY                    1108
#define IDC_SHOOTNUMBER                 1109
#define IDC_BEAMTIME                    1110
#define IDC_RECHARGETIME                1111
#define IDC_BONUS                       1112
#define IDC_PIERCING                    1113
#define IDC_POLARISATION                1114
#define IDC_SHIELDRECHARGE              1115
#define IDC_PENETRATING                 1116
#define IDC_DOUBLESHIELDDMG             1117
#define IDC_DOUBLEHULLDMG               1118
#define IDC_IGNOREALLSHIELDS            1119
#define IDC_COLLAPSESHIELDS             1120
#define IDC_REDUCEMANEUVER              1121
#define IDC_MICROTORP                   1122
#define IDC_COMBO1                      1123

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
