//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by botf2.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDS_SOCKETS_INIT_FAILED      102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDR_BOTF2TYPE                   129
#define IDD_NEWGAME                     129
#define IDD_CHOOSERACE                  130
#define IDD_DIALOG1                     131
#define IDD_PLAYING                     131
#define IDC_CURSOR                      175
#define IDD_CHATDLG                     182
#define IDD_DIALOG2                     183
#define IDD_SEARCHSERVERS               183
#define IDB_LOGO                        188
#define IDD_PREFERENCESDLG              189
#define IDC_CLIENT                      1001
#define IDC_SERVER                      1002
#define IDC_HOSTIP                      1003
#define IDC_HOSTPORT                    1004
#define IDC_SERVERPORT                  1005
#define IDC_USERNAME                    1006
#define IDC_RACE                        1007
#define IDC_RACE2                       1008
#define IDC_RACE3                       1009
#define IDC_RACE4                       1010
#define IDC_RACE5                       1011
#define IDC_RACE6                       1012
#define IDC_SEND                        1013
#define IDC_CHOOSEFILE                  1013
#define IDC_ENDOFROUND                  1014
#define IDC_TEXT                        1015
#define IDC_CHAT                        1016
#define IDC_MSG                         1017
#define IDC_TOALL                       1019
#define IDC_TOPLAYER1                   1020
#define IDC_TOPLAYER2                   1021
#define IDC_SERVER1                     1021
#define IDC_TOPLAYER3                   1022
#define IDC_SERVER2                     1022
#define IDC_TOPLAYER4                   1023
#define IDC_SERVER3                     1023
#define IDC_TOPLAYER5                   1024
#define IDC_SERVER4                     1024
#define IDC_TOPLAYER6                   1025
#define IDC_SERVER5                     1025
#define IDC_MESSAGE                     1025
#define IDC_SERVER6                     1026
#define IDC_CLOSE                       1026
#define IDC_LABEL_COMPUTER              1027
#define ID_LOAD_GAME                    1028
#define IDC_NAME1                       1028
#define IDC_NAME2                       1029
#define IDC_LOAD                        1029
#define IDC_NAME3                       1030
#define IDC_FILENAME                    1030
#define IDC_NAME4                       1031
#define IDC_NAME5                       1032
#define IDC_SAVE                        1032
#define IDC_DESCRIPTION                 1032
#define IDC_LBL_HOSTPORT                1033
#define IDC_NAME6                       1034
#define IDC_PUBLISH                     1034
#define IDC_SEARCHSERVERS               1035
#define IDC_LBL_SERVERPORT              1036
#define IDC_SERVERS                     1037
#define IDC_LOGO                        1037
#define ID_SHOWOPTIONSDLG               1037
#define IDC_LBL_HOSTIP                  1038
#define IDC_CUSTOM1                     1038
#define IDC_LBL_FILENAME                1039
#define IDC_CHECK_AUTOSAVE              1039
#define IDC_LBL_DESCRIPTION             1040
#define IDC_SLIDER_DIFFICULTY           1040
#define IDC_TAB1                        1041
#define IDC_STATIC_DIFFICULTY           1041
#define IDC_CHECK_HARDWARESOUND         1042
#define IDC_CHECK_SOUND                 1043
#define IDC_CHECK_MUSIC                 1044
#define IDC_SLIDER_MUSICVOLUME          1045
#define IDC_SLIDER_TOOLTIPDELAY         1046
#define IDC_CHECK_SHOWTRADEROUTES       1047
#define IDC_CHECK_ANIMATEDICON          1048
#define IDC_CHECK_SHOWSCROLLBARS        1049
#define IDC_CHECK_INVERTNOUSE           1050
#define IDC_EDIT_RANDOMSEED             1051
#define IDC_SLIDER_STARDENSITY          1052
#define IDC_SLIDER_MINORDENSITY         1053
#define IDC_CHECK_HIDEMENUBAR           1054
#define IDC_SLIDER_ANOMALYDENSITY       1055
#define IDC_CHECK_VC_ELIMINATION        1056
#define IDC_CHECK_VC_DIPLOMACY          1057
#define IDC_CHECK_VC_CONQUEST           1058
#define IDC_CHECK_VC_RESEARCH           1059
#define IDC_CHECK_VC_COMBAT             1060
#define IDC_CHECK_VC_SABOTAGE           1061
#define ID_OPTIONEN                     32773
#define ID_INFORMATION                  32774
#define ID_DATENBANK                    32775
#define ID_IMPERIUM                     32776
#define ID_STATISTIK                    32777
#define ID_CHAT                         32778
#define ID_GALAXIE                      32779
#define ID_SYSTEM                       32780
#define ID_RESEARCH                     32781
#define ID_INTELLIGENCE                 32782
#define ID_DIPLOMACY                    32783
#define ID_TRADE                        32784
#define ID_HELP_MANUAL                  32785
#define ID_HELP_CREDITS                 32786
#define ID_HELP_README                  32787
#define ID_HELP_CREDITS32788            32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
