//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BuildingEditor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BUILDINGEDITOR_DIALOG       102
#define IDD_INFODLG                     103
#define IDD_PREREQUISITESDLG            104
#define IDD_PRODUCTIONDLG               105
#define IDD_SPECIALDLG                  106
#define IDR_MAINFRAME                   128
#define IDC_LIST                        1000
#define IDC_RUNNINGNUMBER               1001
#define IDC_RACE                        1002
#define IDC_NAME                        1003
#define IDC_DESCRIPTION                 1004
#define IDC_GRAPHICFILE                 1005
#define IDC_TYPE_A                      1006
#define IDC_TYPE_B                      1007
#define IDC_TYPE_C                      1008
#define IDC_TYPE_E                      1009
#define IDC_TYPE_F                      1010
#define IDC_TYPE_G                      1011
#define IDC_TYPE_H                      1012
#define IDC_TYPE_I                      1013
#define IDC_TYPE_J                      1014
#define IDC_TYPE_K                      1015
#define IDC_TYPE_L                      1016
#define IDC_TYPE_M                      1017
#define IDC_TYPE_N                      1018
#define IDC_TYPE_O                      1019
#define IDC_TYPE_P                      1020
#define IDC_TYPE_Q                      1021
#define IDC_TYPE_R                      1022
#define IDC_TYPE_S                      1023
#define IDC_TYPE_T                      1024
#define IDC_TYPE_Y                      1025
#define IDC_MAXSYSNUMBER                1026
#define IDC_MAXSYSID                    1027
#define IDC_MAXEMPIRENUMBER             1028
#define IDC_MAXEMPIREID                 1029
#define IDC_MINSYSNUMBER                1030
#define IDC_MINSYSID                    1031
#define IDC_MINEMPIRENUMBER             1032
#define IDC_MINEMPIREID                 1033
#define IDC_ONLYHOMESYSTEM              1034
#define IDC_ONLYOWNCOLONY               1035
#define IDC_ONLYMINORRACESYS            1036
#define IDC_ONLYCONQUEREDSYS            1037
#define IDC_REALLYONLYRACE              1038
#define IDC_ONLYINSYSWITHNAME           1039
#define IDC_MINHABITANTS                1040
#define IDC_NEEDEDSYSTEMS               1041
#define IDC_BIOTECH                     1042
#define IDC_ENERGYTECH                  1043
#define IDC_COMPTECH                    1044
#define IDC_PROPULSIONTECH              1045
#define IDC_CONSTRUCTIONTECH            1046
#define IDC_WEAPONTECH                  1047
#define IDC_NEEDEDIP                    1048
#define IDC_NEEDEDENERGY                1049
#define IDC_NEEDEDTITAN                 1050
#define IDC_NEEDEDDEUTERIUM             1051
#define IDC_NEEDEDDURANIUM              1052
#define IDC_NEEDEDCRYSTALS              1053
#define IDC_NEEDEDIRIDIUM               1054
#define IDC_NEEDEDDILITHIUM             1055
#define IDC_SPPROD                      1056
#define IDC_NEEDEDFOODBONI              1056
#define IDC_FPPROD                      1057
#define IDC_NEEDEDENERGYBONI            1057
#define IDC_TITANPROD                   1058
#define IDC_NEEDEDTITANBONI             1058
#define IDC_DEUTERIUMPROD               1059
#define IDC_NEEDEDDEUTERIUMBONI         1059
#define IDC_DURANIUMPROD                1060
#define IDC_NEEDEDDURANIUMBONI          1060
#define IDC_CRYSTALPROD                 1061
#define IDC_NEEDEDCRYSTALSBONI          1061
#define IDC_IRIDIUMPROD                 1062
#define IDC_NEEDEDIRIDIUM2              1062
#define IDC_NEEDEDIRIDIUMBONI           1062
#define IDC_DILITHIUMPROD               1063
#define IDC_NEEDEDDERITIUMBONI          1063
#define IDC_LATINUMPROD                 1064
#define IDC_ENERGYPROD                  1065
#define IDC_IPPROD                      1066
#define IDC_FOODPROD                    1067
#define IDC_SPBONI                      1068
#define IDC_FPBONI                      1069
#define IDC_TITANBONI                   1070
#define IDC_DEUTERIUMBONI               1071
#define IDC_DURANIUMBONI                1072
#define IDC_CRYSTALBONI                 1073
#define IDC_IRIDIUMBONI                 1074
#define IDC_DILITHIUMBONI               1075
#define IDC_LATINUMBONI                 1076
#define IDC_ENERGYBONI                  1077
#define IDC_IPBONI                      1078
#define IDC_FOODBONI                    1079
#define IDC_ALLRESBONI                  1080
#define IDC_BIOTECHBONI                 1081
#define IDC_ENERGYTECHBONI              1082
#define IDC_COMPTECHBONI                1083
#define IDC_PROPULSIONTECHBONI          1084
#define IDC_CONSTRUCTIONTECHBONI        1085
#define IDC_WEAPONTECHBONI              1086
#define IDC_INNERSECURITYBONI           1087
#define IDC_ECONOMYSPYBONI              1088
#define IDC_ECONOMYSABOTAGEBONI         1089
#define IDC_RESEARCHSPYBONI             1090
#define IDC_RESEARCHSABOTAGEBONI        1091
#define IDC_MILITARYSPYBONI             1092
#define IDC_MILITARYSABOTAGEBONI        1093
#define IDC_MORALINSYS                  1094
#define IDC_MORALEMPIREWIDE             1095
#define IDC_SHIPYARD                    1096
#define IDC_BARRACKS                    1097
#define IDC_SHIPYARDBUILDSPEED          1098
#define IDC_BARRACKSBUILDSPEED          1099
#define IDC_BUILDABLESHIPTYPES          1100
#define IDC_HITPOINTS                   1101
#define IDC_SHIELDPOWER                 1102
#define IDC_SHIELDPOWERBONI             1103
#define IDC_SHIPDEFENCE                 1104
#define IDC_SHIPDEFENCEBONI             1105
#define IDC_GROUNDDEFENCE               1106
#define IDC_GROUNDDEFENCEBONI           1107
#define IDC_SHIPTRAINING                1108
#define IDC_TROOPTRAINING               1109
#define IDC_SCANPOWERBONI               1110
#define IDC_SCANRANGEBONI               1111
#define IDC_SCANPOWER                   1112
#define IDC_SCANRANGE                   1113
#define IDC_RESISTANCE                  1114
#define IDC_ADDEDTRADEROUTES            1115
#define IDC_INCOMEONTRADEROUTES         1116
#define IDC_SHIPRECYCLING               1117
#define IDC_BUILDINGSPEEDBONI           1118
#define IDC_UPGRADESPEEDBONI            1119
#define IDC_SHIPSPEEDBONI               1120
#define IDC_TROOPSPEEDBONI              1121
#define IDC_UPGRADEABLE                 1122
#define IDC_FOODDIST                    1122
#define IDC_PREDECESSORID               1123
#define IDC_TITANDIST                   1123
#define IDC_ALLWAYS_ONLINE              1124
#define IDC_DEUTERIUMDIST               1124
#define IDC_NEEDWORKER                  1125
#define IDC_DURANIUMDIST                1125
#define IDC_NEVERREADY                  1126
#define IDC_CRYSTALDIST                 1126
#define IDC_FED_EQU                     1127
#define IDC_IRIDIUMDIST                 1127
#define IDC_FER_EQU                     1128
#define IDC_DERITIUMDIST                1128
#define IDC_KLI_EQU                     1129
#define IDC_SCANINTERFER                1129
#define IDC_ROM_EQU                     1130
#define IDC_CAR_EQU                     1131
#define IDC_DOM_EQU                     1132
#define IDC_LOAD                        1133
#define IDC_SAVE                        1134
#define IDC_NEW                         1135
#define IDC_DELETE                      1136
#define IDC_COPY                        1137
#define IDC_MOVEUP                      1138
#define IDC_MOVEDOWN                    1139
#define IDC_LANGUAGE                    1140
#define IDC_TAB1                        1141
#define IDC_EQUI1NAME                   1143
#define IDC_EQUI2NAME2                  1144
#define IDC_EQUI3NAME3                  1145
#define IDC_EQUI4NAME4                  1146
#define IDC_EQUI5NAME5                  1148
#define IDC_EQUI6NAME6                  1149
#define IDC_NAME2						1150
#define IDC_DESCRIPTION2                1151
#define IDC_MOVEUP_TEN                  1152
#define IDC_MOVEDOWN_TEN                1153
#define IDC_STARTBUILDING               1154
#define IDC_CREATESTART					1155   //better would be to get Start Buildings out of Buildings.data than out of StartBuildings.data

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
